name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose src/main/main.c src/libchessviz/chessviz.c src/libchessviz/chessviz.h && git diff --exit-code

      - name: Build application
        run: make

      - name: Test application
        run: make test

      - name: Run Test
        run: ./bin/chessviz-test


